package com.company;

public enum ProjectParams {
    BIN_PATH,
    OUTPUT_PATH,
    WINDOW_WIDTH,
    WINDOW_HEIGHT,
    WINDOW_AUTO_SIZE,
    FONT_SIZE,
    WINDOW_BACKGROUND_COLOR,
    WINDOW_FONT_COLOR,
    BUTTON_BACKGROUND_COLOR,
    BUTTON_FONT_COLOR,
    SELECTED_LINE_BACKGROUND_COLOR,
    SELECTED_LINE_FONT_COLOR,
    DOUBLES_COUNT
}
